#!/usr/bin/env python3
"""
Plot fitness history from CSV file generated by training scripts.
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import sys

def plot_fitness_comparison(csv_path1, csv_path2, output_path=None):
    """
    Plot comparison of two fitness history CSV files.

    Args:
        csv_path1: Path to fitness_history.csv (original)
        csv_path2: Path to fitness_history_batch.csv (batched)
        output_path: Optional path to save the plot (if None, displays instead)
    """
    # Read both CSVs
    df1 = pd.read_csv(csv_path1) if csv_path1.exists() else None
    df2 = pd.read_csv(csv_path2) if csv_path2.exists() else None

    # Create figure
    fig, ax = plt.subplots(1, 1, figsize=(12, 6))

    # Plot original if it exists
    if df1 is not None:
        window_size = max(10, len(df1) // 50)
        if len(df1) >= window_size:
            df1['smoothed'] = df1['avg_fitness'].rolling(window=window_size, center=True).mean()
            ax.plot(df1['generation'], df1['smoothed'], linewidth=2, label='Original (batch_size=32)', alpha=0.7)
        else:
            ax.plot(df1['generation'], df1['avg_fitness'], linewidth=2, label='Original (batch_size=32)', alpha=0.7)

    # Plot batched if it exists
    if df2 is not None:
        window_size = max(10, len(df2) // 50)
        if len(df2) >= window_size:
            df2['smoothed'] = df2['avg_fitness'].rolling(window=window_size, center=True).mean()
            ax.plot(df2['generation'], df2['smoothed'], linewidth=2, label='Batched (batch_size=512)', alpha=0.7)
        else:
            ax.plot(df2['generation'], df2['avg_fitness'], linewidth=2, label='Batched (batch_size=512)', alpha=0.7)

    ax.set_xlabel('Generation')
    ax.set_ylabel('Average Fitness')
    ax.set_title('Fitness History Comparison: Original vs Batched')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()

    # Save or display
    if output_path:
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"Plot saved to: {output_path}")
    else:
        plt.show()

    # Print statistics for both
    if df1 is not None:
        print("\nOriginal (batch_size=32) Statistics:")
        print(f"  Initial fitness: {df1['avg_fitness'].iloc[0]:.4f}")
        print(f"  Final fitness: {df1['avg_fitness'].iloc[-1]:.4f}")
        print(f"  Improvement: {df1['avg_fitness'].iloc[-1] - df1['avg_fitness'].iloc[0]:.4f}")
        print(f"  Best fitness: {df1['avg_fitness'].max():.4f}")
        print(f"  Total generations: {len(df1)}")

    if df2 is not None:
        print("\nBatched (batch_size=512) Statistics:")
        print(f"  Initial fitness: {df2['avg_fitness'].iloc[0]:.4f}")
        print(f"  Final fitness: {df2['avg_fitness'].iloc[-1]:.4f}")
        print(f"  Improvement: {df2['avg_fitness'].iloc[-1] - df2['avg_fitness'].iloc[0]:.4f}")
        print(f"  Best fitness: {df2['avg_fitness'].max():.4f}")
        print(f"  Total generations: {len(df2)}")


def main():
    # Default paths
    checkpoint_dir = Path('./checkpoints_mnist')
    csv_path1 = checkpoint_dir / 'fitness_history.csv'
    csv_path2 = checkpoint_dir / 'fitness_history_batch.csv'

    # Check if at least one file exists
    if not csv_path1.exists() and not csv_path2.exists():
        print(f"Error: No CSV files found in {checkpoint_dir}")
        print(f"Looking for:")
        print(f"  - {csv_path1}")
        print(f"  - {csv_path2}")
        sys.exit(1)

    # Determine output path
    output_path = checkpoint_dir / 'fitness_comparison.png'

    print(f"Comparing fitness histories:")
    if csv_path1.exists():
        print(f"  Original: {csv_path1}")
    if csv_path2.exists():
        print(f"  Batched: {csv_path2}")

    plot_fitness_comparison(csv_path1, csv_path2, output_path)


if __name__ == "__main__":
    main()
